name: Azure Static Web App Deploy

on:
  push:
    branches:
      - mySQL  # gałąź, którą deployujemy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Deploy to Azure Static Web App'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          #### Poniżej ustaw foldery dla prostej strony:
          app_location: "/"       # folder ze stroną (root repo)
          api_location: ""        # brak backendu
          output_location: "/"    # brak build folderu
